### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by bitterbunny** [jbangert/nail#2]
Hi, nail looks really interesting, but I'm having problems building. They seem to be "environmental". I'm happy to split this into multiple issues if that's better for you.

The first problems are the implicit dependencies on boost and hammer. I worked around them by soft linking `boost -> /opt/local/include/boost` and `hammer -> ../hammer/src/` in the workspace root. From what I can tell the hammer dependency is unneeded, but still included by `grammer.c` and `parser_test.c`.

The problem I haven't worked out is that I get error from the way ld used for `parser_template`, like so:

    ld -r -o parser_template.c.o --format=binary parser_template.c
    ld: unknown option: --format=binary
    make: *** [parser_template.c.o] Error 1

A reasonable amount of googling hasn't turned up what version of ld support `--format`. I'm running on OSX Mavericks 10.9.5. Ld version says:

    $ ld -v
    @(#)PROGRAM:ld  PROJECT:ld64-241.9
    configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7m armv7em
    LTO support using: LLVM version 3.5svn 

I'm happy to help any way I can (splitting issues, pull requests, etc.) Thanks.

**Comment by jbangert** [comment]
Hey! Sorry for the late response, I've been off at a conference. I pushed a few new changes (unrelated, halfway done code in /network, and the new C++ backend - use the old C style Nail with ./cnail ). 
There is a dependency on boost (I use Arch linux and ubuntu, and both support system wide installs of boost), and removed the (last remaining, code-smelly and unused) include of hammer -- let me know if it still does not work.


As to ld, what ld --format=binary does is create an object file that has a single symbol which contains the file given as an argument - which was the quickest way at the time to include the parser templates as a string. When I have a moment, I'll look into a way to do this more portably - probably using XXD and inc files...

**Comment by gopi-pmk** [comment]
hey ,
i get this error , ld -r -o parser_template.c.o --format=binary parser_template.c
ld: unknown option: --format=binary
make: *** [parser_template.c.o] Error 1
my ld -v shows 
@(#)PROGRAM:ld  PROJECT:ld64-236.3
configured to support archs: i386 x86_64 x86_64h armv6 armv7 armv7s armv7m arm64
LTO support using: LLVM version 3.5.2
 let me know how to proceed .
Thanks

**Comment by bitterbunny** [comment]
@gopi-pmk 
This error seems to be caused by using the Mac OS X compiler instead of GCC. I haven't worked around it myself. Julian says above that he plans to make a portable way to handle it.

In the meantime, you could try installing GCC and building with it. I can't give steps to do that other than google.

**Comment by jbangert** [comment]
It took me a while to get around to the second half of the issue -- see the last few commits I pushed. I now embed the templates with XXD as opposed to LD (which turns out to be a GNU ld + ELF specific feature).

**Comment by gopi-pmk** [comment]
Thank you guys , compilation worked !! will try out some examples and see how it goes.
